"""
Title:Hydrologic–Hydrodynamic Flood Inundation Modeling Enhanced by IoT Water-Level Measurements in a Data-Scarce Basin
Author: Shrouq abuismail, github: ShrouqAbuismail
Date:20/04/2026
Description: A Machine-learning based tool for the paper titled "Hydrologic–Hydrodynamic Flood Inundation Modeling Enhanced by IoT Water-Level Measurements in a Data-Scarce Basin" 
"""
"""
SM_IoT Transfer Learning Model/ GitHub Version
--------------------------------------------------
This script trains and evaluates a two-branch ConvLSTM model for
flood inundation (water depth) prediction.
Model structure:
- SM branch: variant + invariant inputs (same structure as SM-Only)
- IoT branch: IoT-derived dynamic inputs
- Fusion head: combines SM and IoT predictions
IMPORTANT:
- Data are not included in this repository.
- Please request access via Google Drive (see README).
Expected data structure:

X_SM_2325_train.npz
X_SM_2325_val.npz
X_SM_2325_test.npz
WD_SM_2325_train.npz
WD_SM_2325_val.npz
WD_SM_2325_test.npz
Times.xlsx
Mask_tensor.npy
DEM.tif
LULC.tif
Mask.tif
Distance_to_river.tif
 <iot_prefix>_train_X.npz
 <iot_prefix>_val_X.npz
 <iot_prefix>_test_X.npz
Variable descriptions:
- X_SM: streamflow-based variant inputs
- WD_SM: water depth outputs generated by HEC-RAS
- IoT: dynamic IoT-based input maps
- 2325: post-2023 dataset
Static spatial inputs:
- DEM
- Manning n roughness (derived from LULC)
- Distance to river
- Domain mask (FEMA 100-year floodplain extent)
--------------------------------------------------
"""
# =============================================================================
# IMPORTS
# =============================================================================
import os
import glob
import json
import argparse
import numpy as np
import pandas as pd
import rasterio
import tensorflow as tf
from tensorflow.keras import Model, Input
from tensorflow.keras.layers import ConvLSTM2D, Dropout, LayerNormalization, Conv2D, Concatenate
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, CSVLogger
from tensorflow.keras.losses import Loss
# =============================================================================
# ARGUMENTS
# =============================================================================
def parse_args():
    p = argparse.ArgumentParser()

    p.add_argument("--data-root", default="data/")
    p.add_argument("--out-dir", default="results/")
    p.add_argument("--run-tag", default="SM_IoT_run")

    # dynamic IoT dataset prefix, e.g. D_A, SD_B, UD2_F, etc.
    p.add_argument("--iot-prefix", default="D_A")

    # optional pretrained SM-Only weights
    p.add_argument("--pretrained-sm", default=None)

    p.add_argument("--epochs", type=int, default=30)
    p.add_argument("--batch-size", type=int, default=2)
    p.add_argument("--learning-rate", type=float, default=1e-4)
    return p.parse_args()
args = parse_args()
BASE_DIR = os.path.abspath(args.data_root)
OUT_DIR = os.path.abspath(args.out_dir)
RUN_TAG = args.run_tag
IOT_PREFIX = args.iot_prefix
PRETRAINED_SM = args.pretrained_sm
EPOCHS = args.epochs
BATCH = args.batch_size
LR = args.learning_rate
os.makedirs(OUT_DIR, exist_ok=True)
# =============================================================================
# HELPERS: GENERIC DATA LOADING
# =============================================================================
def load_common_times(dirpath):
    xlsx = glob.glob(os.path.join(dirpath, "Times.xlsx"))
    if xlsx:
        p = xlsx[0]
        return (
            pd.read_excel(p, sheet_name="Train")["Date"].astype(str).tolist(),
            pd.read_excel(p, sheet_name="Val")["Date"].astype(str).tolist(),
            pd.read_excel(p, sheet_name="Test")["Date"].astype(str).tolist(),
        )

    jsn = glob.glob(os.path.join(dirpath, "common_times.json"))
    if jsn:
        with open(jsn[0], "r") as f:
            d = json.load(f)
        return d["train"], d["val"], d["test"]

    npz = glob.glob(os.path.join(dirpath, "common_times.npz"))
    if npz:
        z = np.load(npz[0], allow_pickle=True)
        return z["train"].tolist(), z["val"].tolist(), z["test"].tolist()
    raise FileNotFoundError("Times.xlsx, common_times.json, or common_times.npz not found.")
def load_array(dirpath, stem):
    npz_path = os.path.join(dirpath, f"{stem}.npz")
    npy_path = os.path.join(dirpath, f"{stem}.npy")
    if os.path.exists(npz_path):
        z = np.load(npz_path, allow_pickle=True)
        if "arr" in z.files:
            return z["arr"]
        return z[z.files[0]]
    if os.path.exists(npy_path):
        return np.load(npy_path, allow_pickle=True)
    raise FileNotFoundError(f"Missing array file for: {stem}")
def fix_y(y):
    """
    Ensure Y shape is (N, H, W, 1)
    """
    y = np.array(y)
    if y.ndim == 4 and y.shape[1] == 1:
        y = np.squeeze(y, axis=1)
        y = y[..., np.newaxis]
    elif y.ndim == 3:
        y = y[..., np.newaxis]
    return y.astype(np.float32)
# =============================================================================
# STATIC DATA
# =============================================================================
def read_and_process_static_data(file_path):
    with rasterio.open(file_path) as src:
        data = src.read(1)
        nodata = src.nodata
        if nodata is not None:
            data[data == nodata] = 0
    return data
def process_static_input(base_path, file_name):
    file_path = os.path.join(base_path, file_name)
    return read_and_process_static_data(file_path)
def crop_to_domain(data, shape=(744, 645)):
    h, w = shape
    return data[:h, :w]
STATIC_FILES = {
    "DEM": "DEM.tif",
    "Manning": "LULC.tif",
    "Mask": "Mask.tif",
    "Distance": "Distance_to_river.tif",
}

def load_static_data(base_path, static_files):
    static_data = {}
    for name, filename in static_files.items():
        data = process_static_input(base_path, filename)
        data = crop_to_domain(data)
        static_data[name] = data.astype(np.float32)
    return static_data
# =============================================================================
# NORMALIZATION
# =============================================================================
def normalize_global(train, val, test):
    mean = np.mean(train)
    std = np.std(train) + 1e-8
    train_n = (train - mean) / std
    val_n = (val - mean) / std
    test_n = (test - mean) / std

    return train_n.astype(np.float32), val_n.astype(np.float32), test_n.astype(np.float32), mean, std
def normalize_static(static_dict):
    """
    Normalize each invariant layer independently.
    """
    static_norm = {}
    static_stats = {}

    for key, data in static_dict.items():
        mean = np.mean(data)
        std = np.std(data) + 1e-8
        static_norm[key] = ((data - mean) / std).astype(np.float32)
        static_stats[key] = {"mean": float(mean), "std": float(std)}
    return static_norm, static_stats
# =============================================================================
# VARIANT + INVARIANT STACKING
# =============================================================================
def stack_invariant_with_variant(x_variant, invariant_dict):
    """
    Concatenate invariant (static) spatial layers to variant (dynamic) inputs.

    x_variant shape: (N, T, H, W, C_v)
    invariant_dict: {name: (H, W)}
    returns: (N, T, H, W, C_v + C_i)
    """
    n, t, h, w, _ = x_variant.shape
    invariant_stack = np.stack(list(invariant_dict.values()), axis=-1)   # (H, W, C_i)
    invariant_stack = invariant_stack[np.newaxis, np.newaxis, ...]       # (1, 1, H, W, C_i)
    invariant_stack = np.repeat(invariant_stack, n, axis=0)              # (N, 1, H, W, C_i)
    return np.concatenate([x_variant, invariant_stack], axis=-1).astype(np.float32)
# =============================================================================
# LOAD DATA
# =============================================================================
# target
Y_train = fix_y(load_array(BASE_DIR, "WD_SM_2325_train"))
Y_val   = fix_y(load_array(BASE_DIR, "WD_SM_2325_val"))
Y_test  = fix_y(load_array(BASE_DIR, "WD_SM_2325_test"))
# SM branch dynamic input
X_train = load_array(BASE_DIR, "X_SM_2325_train").astype(np.float32)
X_val   = load_array(BASE_DIR, "X_SM_2325_val").astype(np.float32)
X_test  = load_array(BASE_DIR, "X_SM_2325_test").astype(np.float32)
# IoT branch dynamic input
IoT_train = load_array(BASE_DIR, f"{IOT_PREFIX}_train_X").astype(np.float32)
IoT_val   = load_array(BASE_DIR, f"{IOT_PREFIX}_val_X").astype(np.float32)
IoT_test  = load_array(BASE_DIR, f"{IOT_PREFIX}_test_X").astype(np.float32)
# times
train_times, val_times, test_times = load_common_times(BASE_DIR)
# =============================================================================
# LOAD STATIC DATA
# =============================================================================
STATIC_DATA = load_static_data(BASE_DIR, STATIC_FILES)
# =============================================================================
# NORMALIZE DATA
# =============================================================================
Y_train, Y_val, Y_test, Y_mean, Y_std = normalize_global(Y_train, Y_val, Y_test)
X_train, X_val, X_test, X_mean, X_std = normalize_global(X_train, X_val, X_test)
IoT_train, IoT_val, IoT_test, IoT_mean, IoT_std = normalize_global(IoT_train, IoT_val, IoT_test)
STATIC_DATA, STATIC_STATS = normalize_static(STATIC_DATA)
# =============================================================================
# STACK INVARIANT DATA WITH SM VARIANT INPUT
# =============================================================================
X_train = stack_invariant_with_variant(X_train, STATIC_DATA)
X_val   = stack_invariant_with_variant(X_val, STATIC_DATA)
X_test  = stack_invariant_with_variant(X_test, STATIC_DATA)
# =============================================================================
# FEMA MASK
# =============================================================================
fp_mask_path = os.path.join(BASE_DIR, "Mask_tensor.npy")
fp_mask_np = np.load(fp_mask_path).astype(np.float32)
# Use floodplain slice if needed
FEMA_MASK = fp_mask_np[1] if fp_mask_np.ndim == 3 else fp_mask_np
FEMA_MASK = crop_to_domain(FEMA_MASK).astype(np.float32)
FEMA_MASK_TF = tf.convert_to_tensor(FEMA_MASK, dtype=tf.float32)
# =============================================================================
# SIMPLE MASKED MSE LOSS 
# =============================================================================
class SimpleMaskedMSE(tf.keras.losses.Loss):
    """
    Mean Squared Error computed only within the FEMA floodplain mask.
    """
    def __init__(self, mask, **kwargs):
        super().__init__(**kwargs)
        self.mask = tf.cast(mask > 0, tf.float32)

    def call(self, y_true, y_pred):

        if y_true.shape.rank == 4:
            y_true = tf.squeeze(y_true, axis=-1)
        if y_pred.shape.rank == 4:
            y_pred = tf.squeeze(y_pred, axis=-1)

        err = tf.square(y_true - y_pred)

        mask = tf.expand_dims(self.mask, axis=0)
        mask = tf.broadcast_to(mask, tf.shape(err))

        return tf.reduce_sum(err * mask) / (
            tf.reduce_sum(mask) + tf.keras.backend.epsilon()
        )
# =============================================================================
# SM BRANCH (PRETRAINED SURROGATE)
# =============================================================================
def build_sm_branch(input_shape):
    inputs = Input(shape=input_shape, name="sm_input")
    x = ConvLSTM2D(8, (3, 3), padding="same", return_sequences=True, name="sm_lstm1")(inputs)
    x = Dropout(0.2, name="sm_dropout1")(x)
    x = LayerNormalization(name="sm_ln1")(x)
    x = ConvLSTM2D(42, (3, 3), padding="same", return_sequences=False, name="sm_lstm2")(x)
    x = Dropout(0.2, name="sm_dropout2")(x)
    x = LayerNormalization(name="sm_ln2")(x)
    outputs = Conv2D(1, (1, 1), activation="linear", padding="same", name="sm_head")(x)
    return Model(inputs=inputs, outputs=outputs, name="SM_Branch")
# =============================================================================
# IOT BRANCH (LEARNED FROM SCRATCH)
# =============================================================================
def build_iot_branch(input_shape):
    inputs = Input(shape=input_shape, name="iot_input")

    x = ConvLSTM2D(8, (3, 3), padding="same", return_sequences=True, name="iot_lstm1")(inputs)
    x = Dropout(0.2, name="iot_dropout1")(x)
    x = LayerNormalization(name="iot_ln1")(x)

    x = ConvLSTM2D(42, (3, 3), padding="same", return_sequences=False, name="iot_lstm2")(x)
    x = Dropout(0.2, name="iot_dropout2")(x)
    x = LayerNormalization(name="iot_ln2")(x)

    outputs = Conv2D(1, (1, 1), activation="linear", padding="same", name="iot_head")(x)

    return Model(inputs=inputs, outputs=outputs, name="IoT_Branch")
# =============================================================================
# FUSION MODEL (TRANSFER LEARNING)
# =============================================================================
def build_sm_iot_fusion_model(sm_input_shape,
                             iot_input_shape,
                             pretrained_sm_path=None,
                             freeze_sm=False):

    # --- build branches ---
    sm_branch = build_sm_branch(sm_input_shape)
    iot_branch = build_iot_branch(iot_input_shape)

    # --- transfer learning: load pretrained SM ---
    if pretrained_sm_path is not None and os.path.exists(pretrained_sm_path):
        sm_branch.load_weights(pretrained_sm_path)
 
        if freeze_sm:
            for layer in sm_branch.layers:
                layer.trainable = False
        
        else:
            print("[INFO] SM branch fine-tuned (recommended)")

    else:
        print("[WARNING] No pretrained SM weights â†’ training from scratch")
    # --- inputs ---
    sm_input = Input(shape=sm_input_shape, name="sm_input")
    iot_input = Input(shape=iot_input_shape, name="iot_input")
    # --- forward ---
    sm_pred = sm_branch(sm_input)
    iot_pred = iot_branch(iot_input)
    # --- fusion ---
    fused = Concatenate(axis=-1, name="fusion_concat")([sm_pred, iot_pred])
    final_output = Conv2D(
        1,
        (1, 1),
        activation="linear",
        padding="same",
        name="fusion_head"
    )(fused)
    model = Model(
        inputs=[sm_input, iot_input],
        outputs=final_output,
        name="SM_IoT_TransferLearning_Model"
    )
    return model
# =============================================================================
# BUILD MODEL
# =============================================================================
SM_INPUT_SHAPE  = X_train.shape[1:]
IOT_INPUT_SHAPE = IoT_train.shape[1:]

model = build_sm_iot_fusion_model(
    sm_input_shape=SM_INPUT_SHAPE,
    iot_input_shape=IOT_INPUT_SHAPE,
    pretrained_sm_path=PRETRAINED_SM,
    freeze_sm=True   # full freezing
)
# =============================================================================
# COMPILE
# =============================================================================
loss_fn = SimpleMaskedMSE(mask=FEMA_MASK_TF)

model.compile(
    optimizer=Adam(learning_rate=LR),
    loss=loss_fn,
)

print("\n[INFO] Model summary:")
model.summary()
# =============================================================================
# CALLBACKS
# =============================================================================
ckpt_path = os.path.join(OUT_DIR, f"{RUN_TAG}_best.h5")
csv_path = os.path.join(OUT_DIR, f"{RUN_TAG}_history.csv")
final_path = os.path.join(OUT_DIR, f"{RUN_TAG}_final.h5")

callbacks = [
    ModelCheckpoint(
        ckpt_path,
        monitor="val_loss",
        save_best_only=True,
        mode="min",
        verbose=1,
    ),
    EarlyStopping(
        monitor="val_loss",
        patience=5,
        mode="min",
        restore_best_weights=True,
        verbose=1,
    ),
    CSVLogger(csv_path, append=False),
]
# =============================================================================
# TRAIN
# =============================================================================
history = model.fit(
    [X_train, IoT_train],
    Y_train,
    validation_data=([X_val, IoT_val], Y_val),
    epochs=EPOCHS,
    batch_size=BATCH,
    callbacks=callbacks,
    verbose=1,
)
# =============================================================================
# SAVE FINAL WEIGHTS
# =============================================================================
model.save_weights(final_path)
