"""
Title:Hydrologic–Hydrodynamic Flood Inundation Modeling Enhanced by IoT Water-Level Measurements in a Data-Scarce Basin
Author: Shrouq abuismail, github: ShrouqAbuismail
Date:20/04/2026
Description: A Machine-learning based tool for the paper titled "Hydrologic–Hydrodynamic Flood Inundation Modeling Enhanced by IoT Water-Level Measurements in a Data-Scarce Basin" 
"""
"""
SM_Only Surrogate Model/ GitHub Version
--------------------------------------------------
This script trains and evaluates a ConvLSTM-based surrogate model
for flood inundation (water depth) prediction.

IMPORTANT:
- Data are not included in this repository.
- Please request access via Google Drive (see README).

Expected data structure:

X_SM_0523_train.npz
X_SM_0523_val.npz
X_SM_0523_test.npz
WD_SM_0523_train.npz
WD_SM_0523_val.npz
WD_SM_0523_test.npz
Mask_tensor.npy
WD_scaler_new.save
Times.xlsx (or json/npz)
DEM_2.tif
LULC_2.tif
Distance_to_river.tif
Mask.tif
Variable descriptions:
- X_SM: streamflow-based input data
- WD_SM: water depth outputs generated by HEC-RAS
- 0523: pre-2023 dataset
Static spatial inputs:
- DEM
- Manning n roughness (derived from LULC)
- Distance to river
- Domain mask (FEMA 100-year floodplain extent)
--------------------------------------------------
"""
# =============================================================================
# IMPORTS
# =============================================================================
import os
import glob
import json
import argparse
import numpy as np
import pandas as pd
import joblib
import tensorflow as tf
import rasterio
from tensorflow.keras import Model, Input
from tensorflow.keras.layers import ConvLSTM2D, Dropout, LayerNormalization, Conv2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.losses import Loss
# =============================================================================
# ARGUMENTS
# =============================================================================
def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--data-root", default="data/")
    p.add_argument("--out-dir", default="results/")
    p.add_argument("--run-tag", default="SM_run")
    p.add_argument("--epochs", type=int, default=30)
    p.add_argument("--batch-size", type=int, default=2)
    return p.parse_args()
args = parse_args()
BASE_DIR = os.path.abspath(args.data_root)
OUT_DIR = os.path.abspath(args.out_dir)
RUN_TAG = args.run_tag
EPOCHS = args.epochs
BATCH = args.batch_size
LR = args.learning_rate
os.makedirs(OUT_DIR, exist_ok=True)
# =============================================================================
# DATA HELPERS
# =============================================================================
def load_common_times(dirpath):
    xlsx = glob.glob(os.path.join(dirpath, "Times.xlsx"))
    if xlsx:
        p = xlsx[0]
        return (
            pd.read_excel(p, "Train")["Date"].astype(str).tolist(),
            pd.read_excel(p, "Val")["Date"].astype(str).tolist(),
            pd.read_excel(p, "Test")["Date"].astype(str).tolist(),
        )
    raise FileNotFoundError("Times file not found")
def load_array(dirpath, name):
    path = os.path.join(dirpath, f"{name}.npz")
    z = np.load(path, allow_pickle=True)
    return z[list(z.files)[0]]
def fix_y(y):
    y = np.array(y)
    if y.ndim == 3:
        y = y[..., np.newaxis]
    return y.astype(np.float32)
# =============================================================================
# STATIC DATA FUNCTIONS
# =============================================================================
def read_and_process_static_data(file_path):
    with rasterio.open(file_path) as src:
        data = src.read(1)
        nodata = src.nodata
        if nodata is not None:
            data[data == nodata] = 0
    return data
def process_static_input(base_path, file_name):
    file_path = os.path.join(base_path, file_name)
    return read_and_process_static_data(file_path)
def crop_to_domain(data, shape=(744, 645)):
    H, W = shape
    return data[:H, :W]
STATIC_FILES = {
    "DEM": "DEM_2.tif",
    "Manning": "LULC_2.tif",
    "Slope": "Slope.tif",
    "Mask": "Mask.tif",
    "Distance": "Distance_to_river.tif",
}
def load_static_data(base_path, static_files):
    static_data = {}
    for name, filename in static_files.items():
        data = process_static_input(base_path, filename)
        data = crop_to_domain(data)
        static_data[name] = data
    return static_data
# =============================================================================
# LOAD WATER DEPTH AND STREAMFLOW DATA
# =============================================================================
Y_train = fix_y(load_array(BASE_DIR, "WD_SM_0523_train"))
Y_val   = fix_y(load_array(BASE_DIR, "WD_SM_0523_val"))
Y_test  = fix_y(load_array(BASE_DIR, "WD_SM_0523_test"))

X_train = load_array(BASE_DIR, "X_SM_0523_train")
X_val   = load_array(BASE_DIR, "X_SM_0523_val")
X_test  = load_array(BASE_DIR, "X_SM_0523_test")
train_times, val_times, test_times = load_common_times(BASE_DIR)
# =============================================================================
# LOAD STATIC DATA
# =============================================================================
STATIC_DATA = load_static_data(BASE_DIR, STATIC_FILES)
# =============================================================================
# FEMA MASK
# =============================================================================
fp_mask_path = os.path.join(BASE_DIR, "Mask_tensor.npy")
fp_mask_np = np.load(fp_mask_path).astype(np.float32)
# Use floodplain slice if needed
FEMA_MASK = fp_mask_np[1] if fp_mask_np.ndim == 3 else fp_mask_np
FEMA_MASK = crop_to_domain(FEMA_MASK).astype(np.float32)
FEMA_MASK_TF = tf.convert_to_tensor(FEMA_MASK, dtype=tf.float32)
# =============================================================================
# DATA NORMALIZATION
# =============================================================================
def normalize_global(train, val, test):
    mean = np.mean(train)
    std = np.std(train) + 1e-8
    train_n = (train - mean) / std
    val_n   = (val - mean) / std
    test_n  = (test - mean) / std
    return train_n, val_n, test_n, mean, std
def normalize_static(static_dict):
    norm_static = {}
    stats = {}
    for key, data in static_dict.items():
        mean = np.mean(data)
        std = np.std(data) + 1e-8

        norm_static[key] = (data - mean) / std
        stats[key] = {"mean": float(mean), "std": float(std)}
    return norm_static, stats
# ---------------------- WATER DEPTH NORMALIZATION ----------------------
Y_train, Y_val, Y_test, Y_mean, Y_std = normalize_global(
    Y_train, Y_val, Y_test
)
# ----------------------STREAMFLOW NORMALIZATION---------------------
X_train, X_val, X_test, X_mean, X_std = normalize_global(
    X_train, X_val, X_test
)
# ----------------------STATIC DATA NORMALIZATION ----------------------
STATIC_DATA, STATIC_STATS = normalize_static(STATIC_DATA)

# =============================================================================
# CONCATENATE VARIANT (DYNAMIC) AND INVARIANT (STATIC) DATA
# =============================================================================
def stack_invariant_with_variant(X_variant, invariant_dict):
    N, T, H, W, C_v = X_variant.shape
    # Stack invariant layers â†’ (H, W, C_i)
    invariant_stack = np.stack(list(invariant_dict.values()), axis=-1)
    # Expand â†’ (1,1,H,W,C_i)
    invariant_stack = invariant_stack[np.newaxis, np.newaxis, ...]
    # Repeat across samples â†’ (N,1,H,W,C_i)
    invariant_stack = np.repeat(invariant_stack, N, axis=0)
    # Concatenate along channel dimension
    X_combined = np.concatenate([X_variant, invariant_stack], axis=-1)
    return X_combined
X_train = stack_invariant_with_variant(X_train, STATIC_DATA)
X_val   = stack_invariant_with_variant(X_val, STATIC_DATA)
X_test  = stack_invariant_with_variant(X_test, STATIC_DATA)
# =============================================================================
# LOSS FUNCTION
# =============================================================================
class SimpleMaskedMSE(tf.keras.losses.Loss):
    """
    Mean Squared Error computed only within the FEMA floodplain mask.
    """
    def __init__(self, mask, **kwargs):
        super().__init__(**kwargs)
        self.mask = tf.cast(mask > 0, tf.float32)

    def call(self, y_true, y_pred):

        if y_true.shape.rank == 4:
            y_true = tf.squeeze(y_true, axis=-1)
        if y_pred.shape.rank == 4:
            y_pred = tf.squeeze(y_pred, axis=-1)

        err = tf.square(y_true - y_pred)

        mask = tf.expand_dims(self.mask, axis=0)
        mask = tf.broadcast_to(mask, tf.shape(err))

        return tf.reduce_sum(err * mask) / (
            tf.reduce_sum(mask) + tf.keras.backend.epsilon()
        )
# =============================================================================
# MODEL
# =============================================================================
H, W = 744, 645
C = X_train.shape[-1]
inputs = Input(shape=(1, H, W, C))

x = ConvLSTM2D(8, (3,3), padding="same", return_sequences=True)(inputs)
x = Dropout(0.2)(x)
x = LayerNormalization()(x)

x = ConvLSTM2D(42, (3,3), padding="same")(x)
x = Dropout(0.2)(x)
x = LayerNormalization()(x)

outputs = Conv2D(1, (1,1))(x)

model = Model(inputs, outputs)
model.summary()

loss_fn = SimpleMaskedMSE(mask=FEMA_MASK_TF)

model.compile(
    optimizer=Adam(learning_rate=LR),
    loss=loss_fn,
)
# =============================================================================
# TRAIN
# =============================================================================
ckpt_path = os.path.join(OUT_DIR, f"{RUN_TAG}_best.h5")  
callbacks = [
    ModelCheckpoint(ckpt_path, save_best_only=True, monitor="val_loss"),
    EarlyStopping(patience=5, restore_best_weights=True),
]
history = model.fit(
    X_train,
    Y_train,
    validation_data=(X_val, Y_val),
    epochs=EPOCHS,
    batch_size=BATCH,
)
# =============================================================================
# SAVE MODEL
# =============================================================================
#SAVE THE WEIGHTS TO BE USED IN THE SM-IOT MODEL
model.save_weights(os.path.join(OUT_DIR, f"{RUN_TAG}_final.h5"))
# =============================================================================
# PREDICTION
# =============================================================================
pred_test = model.predict(X_test)
np.savez_compressed(
    os.path.join(OUT_DIR, f"{RUN_TAG}_pred_test.npz"),
    pred=pred_test,
    time=np.array(test_times, dtype=object),
)
# =============================================================================
# EVALUATION METRICS
# =============================================================================
def RMSE_MEDIAN(true_event, pred_event, cell_indices):
    
    rmse_cells = []

    for (i, j) in cell_indices:
        true_series = true_event[:, i, j]
        pred_series = pred_event[:, i, j]

        # Skip inactive cells
        if np.all(true_series == 0) and np.all(pred_series == 0):
            continue

        mse = np.mean((true_series - pred_series) ** 2)
        rmse_cells.append(np.sqrt(mse))

    return rmse_cells
def BIAS_MEDIAN(true_event, pred_event, cell_indices):
    """
    Compute mean bias per cell over the event.
    """
    biases = []

    for (i, j) in cell_indices:
        true_series = true_event[:, i, j]
        pred_series = pred_event[:, i, j]

        if np.all(true_series == 0) and np.all(pred_series == 0):
            continue

        biases.append(np.mean(pred_series - true_series))

    return biases
def TIMEIDFF(true_event,
                                  pred_event,
                                  cell_indices,
                                  dt=1.0,
                                  return_abs=True,
                                  eps=1e-6):
    """
    Compute peak timing difference per cell.
    Returns time difference (e.g., hours).
    """
    dt_cells = []

    for (i, j) in cell_indices:
        true_series = true_event[:, i, j]
        pred_series = pred_event[:, i, j]

        # Skip dry cells
        if np.max(true_series) <= eps or np.max(pred_series) <= eps:
            continue

        t_true_peak = int(np.argmax(true_series))
        t_pred_peak = int(np.argmax(pred_series))

        diff_time = (t_pred_peak - t_true_peak) * dt

        if return_abs:
            diff_time = abs(diff_time)

        dt_cells.append(diff_time)

    return dt_cells
def PEAKDIFF(true_event, pred_event, cell_indices, eps=1e-6):
    """
    Compute peak magnitude difference per cell based on maximum water depth
    over the entire event.

    Parameters
    ----------
    true_event : array (T, H, W)
    pred_event : array (T, H, W)
    cell_indices : list of (i, j)

    Returns
    -------
    list of peak differences (pred - true)
    """
    peak_diffs = []

    for (i, j) in cell_indices:
        true_series = true_event[:, i, j]
        pred_series = pred_event[:, i, j]

        # Skip dry cells
        if np.max(true_series) <= eps and np.max(pred_series) <= eps:
            continue

        true_peak = np.max(true_series)
        pred_peak = np.max(pred_series)

        peak_diffs.append(pred_peak - true_peak)

    return peak_diffs